- hosts: test
  become: true
  tasks:
  - name: Install aptitude using apt
    apt: 
      name=aptitude
      state=latest 
      update_cache=yes 
      force_apt_get=yes
  - name: install postfix
    apt: 
      name: postfix
      state: present
    tags: 
    - init postfix
  - name: delete postfix
    apt: 
      name: postfix    
      state: absent
    tags:  
    - drop postfix
