- hosts: test
  become: true
  vars_files:
    - users_pass.yml
  tasks:
  - name: Add Group 'superusers'
    ansible.builtin.user:
      name: superusers
      state: present
  - name: Create users
    ansible.builtin.user:
      name: "{{ item }}"
      group: superusers
      password: $6$PaaN8W.Z/0EBBnOn$66WmaYUtX7l1XMl46mMRP3ewyUC.lKNFvNGgsmYgsM9MQ8o/KDXdM151Lb/xtDxL6vURZSK1ukVO2jJAvgYVC/
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /home/user1/.ssh/id_rsa.pub
    with_items:
      - "{{ names }}"
  - name: Validate the sudoers file before saving
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%superusers ALL='
      line: '%superusers ALL=(ALL:ALL) ALL'
      validate: /usr/sbin/visudo -cf %s
